---
title: "The Monty Hall problem for sceptics"
author: Joan Marine-Boada
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### The Problem

The [Monty Hall problem](https://en.wikipedia.org/wiki/Monty_Hall_problem) is named for its similarity to the *Let's Make a Deal* television game show hosted by *Monty Hall*. The problem is stated as follows. Assume that a room is equipped with three doors, A, B and C. Behind two are goats, and behind the third is a shiny new car. You are asked to pick a door, and will win whatever is behind it. Let's say you pick door A. Before the door is opened, however, someone who knows what's behind the doors (Monty Hall) opens one of the other two doors, revealing a goat, and asks you if you wish to change your selection to the third door (i.e., the door which neither you picked nor he opened). The Monty Hall problem is deciding whether you do.

### The Solution

The correct answer is that you do want to switch. If you do not switch, you have the expected $1/3$ chance of winning the car, since no matter whether you initially picked the correct door, Monty Hall will show you a door with a goat. But after Monty has eliminated one of the doors for you, you obviously do not improve your chances of winning to better than $1/3$ by sticking with your original choice. If you now switch doors, however, there is a $2/3$ chance you will win the car (counterintuitive though it seems).

Let's write it with some mathematical rigour:

We suppose we have three doors: $A$, $B$ and $C$. And our choice is, for instance, the door $A$.
Now we define the following events:

- $C_A$ = the car is behind the door $A$.
- $C_B$ = the car is behind the door $B$.
- $C_C$ = the car is behind the door $C$.

Since we assume that this is a fair game, we must assume that:

$$ P(C_A) = P(C_B) = P(C_C) = 1/3$$
Finally, we define the event that we want to know its probability:

- $WIC$ = winning the game if we decide to change the door.

Calculating this probability is easy using the [Law of Total Probability](https://en.wikipedia.org/wiki/Law_of_total_probability), and assuming we have choosen the door $A$:

$$\begin{align}
P(WIC) &= P(WIC | C_A) \cdot P(C_A) + P(WIC | C_B) \cdot P(C_B) + P(WIC | C_C) \cdot P(C_C)=\\
&= 0 \cdot 1/3 + 1 \cdot 1/3 + 1 \cdot 1/3 =\\
&= 2/3
\end{align}
$$



